import { CoordinatePanelTexts } from '../types'

export const COORDINATE_PANEL_TEXTS: CoordinatePanelTexts = {
  title: 'Coordinates',
  addPoint: 'Add Point',
  editPoint: 'Edit Point',
  removePoint: 'Remove Point',
  actions: 'Actions',
  clearGeometries: 'Clear Geometries',
  index: 'Index',
  x: 'X',
  y: 'Y',
  azimuth: 'Azimuth',
  distance: 'Distance',
  noPoints: 'No points added',
  addPointTitle: 'Add Point',
  editPointTitle: 'Edit Point',
  removePointTitle: 'Remove Point',
  clearGeometriesTitle: 'Clear Geometries',
  addPointDescription: 'Add a new point to the list',
  editPointDescription: 'Edit the selected point',
  removePointDescription: 'Remove the selected point',
  clearGeometriesDescription: 'Clear all geometries from the map',

  memorialDescriptive: 'Descriptive Memorial',
  referenceSystem: 'Reference System',
  selectSystem: 'Select system',
  sirgas2000: 'SIRGAS 2000',
  coordinateFormat: 'Coordinate Format',
  selectFormat: 'Select format',
  decimalDegrees: 'Decimal Degrees (DD)',
  degreesMinutesSeconds: 'Degrees, Minutes, Seconds (DMS)',
  manualInput: 'Manual Input',
  insertCoordinates: 'Insert Coordinates',
  xLongitude: 'X (Longitude)',
  yLatitude: 'Y (Latitude)',
  degrees: 'Degrees',
  minutes: 'Minutes',
  seconds: 'Seconds',
  addedPoints: 'Added Points',
  finalizeGeometry: 'Finalize Geometry',
  csvUpload: 'CSV Upload',
  csvFileUpload: 'CSV File Upload',
  dragCsvFile: 'Drag CSV file or click to upload',
  csvColumnsInfo: 'The file must contain the columns: X, Y, AZIMUTH, DISTANCE',
  applyCsvCoordinates: 'Apply CSV Coordinates',

  shapefileUpload: 'Shapefile Upload',
  shapefileFileUpload: 'Shapefile Upload',
  dragShapefileZip: 'Drag ZIP file or click to upload',
  shapefileZipInfo:
    'Upload a .zip with .shp, .shx and .dbf containing a single Polygon or MultiPolygon geometry',
  shapefileAppliedSuccess: 'Shapefile applied successfully',

  placeholderLongitude: 'e.g., -46.6333',
  placeholderLatitude: 'e.g., -23.5505',
  placeholderAzimuth: 'e.g., 90',
  placeholderDistance: 'e.g., 100',
  placeholderDegrees: 'Degrees',
  placeholderMinutes: 'Minutes',
  placeholderSeconds: 'Seconds',

  errorXYRequired: 'X and Y are required for the first point',
  errorDegreesRequired: 'Degrees are required for the first point',
  errorFirstRowXY: 'The first row of the CSV must contain X and Y coordinates',
  errorProvideCoordinatesOrAzimuthDistance: 'Provide coordinates or Azimuth and Distance'
}
