import { CoordinatePanelTexts } from "../types";

export const COORDINATE_PANEL_TEXTS: CoordinatePanelTexts = {
  title: 'Coordenadas',
  addPoint: 'Adicionar Ponto',
  editPoint: 'Editar Ponto',
  removePoint: 'Remover Ponto',
  actions: 'Ações',
  clearGeometries: 'Limpar Geometrias',
  index: 'Índice',
  x: 'X',
  y: 'Y',
  azimuth: 'Azimute',
  distance: 'Distância',
  noPoints: 'Nenhum ponto adicionado',
  addPointTitle: 'Adicionar Ponto',
  editPointTitle: 'Editar Ponto',
  removePointTitle: 'Remover Ponto',
  clearGeometriesTitle: 'Limpar Geometrias',
  addPointDescription: 'Adicionar um novo ponto à lista',
  editPointDescription: 'Editar o ponto selecionado',
  removePointDescription: 'Remover o ponto selecionado',
  clearGeometriesDescription: 'Limpar todas as geometrias do mapa',

  memorialDescriptive: 'memorial descritivo',
  referenceSystem: 'Sistema de Referência',
  selectSystem: 'Selecione o sistema',
  sirgas2000: 'SIRGAS 2000',
  coordinateFormat: 'Formato de Coordenadas',
  selectFormat: 'Selecione o formato',
  decimalDegrees: 'Graus Decimais (DD)',
  degreesMinutesSeconds: 'Graus, Minutos, Segundos (DMS)',
  manualInput: 'Preenchimento Manual',
  insertCoordinates: 'Inserir Coordenadas',
  xLongitude: 'X (Longitude)',
  yLatitude: 'Y (Latitude)',
  degrees: 'Graus',
  minutes: 'Minutos',
  seconds: 'Segundos',
  addedPoints: 'Pontos Adicionados',
  finalizeGeometry: 'Finalizar Geometria',
  csvUpload: 'Upload CSV',
  csvFileUpload: 'Upload de Arquivo CSV',
  dragCsvFile: 'Arraste o arquivo CSV ou clique para fazer upload',
  csvColumnsInfo: 'O arquivo deve conter as colunas: X, Y, AZIMUTH, DISTANCIA',
  applyCsvCoordinates: 'Aplicar Coordenadas do CSV',

  placeholderLongitude: 'Ex: -46.6333',
  placeholderLatitude: 'Ex: -23.5505',
  placeholderAzimuth: 'Ex: 90',
  placeholderDistance: 'Ex: 100',
  placeholderDegrees: 'Graus',
  placeholderMinutes: 'Minutos',
  placeholderSeconds: 'Segundos',

  errorXYRequired: 'X e Y são obrigatórios no primeiro ponto',
  errorDegreesRequired: 'Graus são obrigatórios no primeiro ponto',
  errorFirstRowXY: 'A primeira linha do CSV deve conter as coordenadas X e Y',
  errorProvideCoordinatesOrAzimuthDistance: 'Forneça coordenadas ou Azimuth e Distância'
}